In [1]:
import warnings
import pandas as pd 
pd.pandas.set_option('display.max_columns', None)
import numpy as np
import os

import warnings
warnings.filterwarnings('ignore')

In [2]:
base_path = '../data/owner_data'

files_list = os.listdir(base_path)

In [3]:
import os
import pandas as pd
from pathlib import Path

def get_sheet_names(base_path):
    base_path = Path(base_path)
    
    if not base_path.is_dir():
        raise NotADirectoryError(f"{base_path} is not a valid directory.")

    res = {}

    for file_path in base_path.glob("*.xls*"):
        try:
            xls = pd.ExcelFile(file_path)
            res[file_path.name] = xls.sheet_names
        except Exception as e:
            print(f"Could not read {file_path.name}: {e}")

    return res

In [4]:
base_path = '../data/owner_data'
available_sheets = get_sheet_names(base_path)

In [5]:
available_sheets

{'Al Barari.xlsx': ['Old', 'Apr to Dec'],
 'Arabian Ranches 1,2,3.xlsx': ['Old', 'Apr to Dec'],
 'Arjan.xlsx': ['Old', 'Apr to Dec'],
 'Bluewater.xlsx': ['Old', 'Apr to Dec'],
 'Business Bay-1.xlsx': ['Old', 'Apr to Dec1'],
 'City Walk.xlsx': ['Old', 'Apr to Dec'],
 'Damac Hills 1.xlsx': ['Old', 'Apr to Dec1'],
 'Damac Hills 2.xlsx': ['Old', 'Apr to Dec'],
 'Damac Lagoon.xlsx': ['Old', 'Apr to Dec'],
 'Deira Island 2025.xlsx': ['Deira Island', 'Bay Villas'],
 'Downtown Views T1, T2 and T3.xlsx': ['Downtown Veiws  (c)',
  'Sheet2',
  'Sheet3'],
 'Downtown.xlsx': ['Old', 'Apr to Dec1'],
 'Dubai Creek Harbour.xlsx': ['Old', 'Apr to Dec'],
 'Dubai Hills.xlsx': ['Old1', 'Apr to Dec'],
 'Dubai South.xlsx': ['Old', 'Apr to Dec1'],
 'Emaar BeachFront.xlsx': ['Old', 'Apr to Dec'],
 'Emaar South.xlsx': ['Old', 'Apr to Dec'],
 'Emirates Living Nov 1.xlsx': ['Old1', 'Apr to Dec1'],
 'Furjan.xlsx': ['Old1', 'Apr to Dec1'],
 'Greens.xlsx': ['Old', 'Apr to Dec'],
 'JBR 2022.xlsx': ['Sheet1', 'Sheet2', 'Sheet3'],
 'JBR.xlsx': ['Old', 'Apr to Dec'],
 'JGE.xlsx': ['Old', 'Apr to Dec1'],
 'JLT.xlsx': ['Old', 'Apr to Dec1'],
 'Jumeirah Bay.xlsx': ['Old', 'Apr to Dec1'],
 'JUMEIRAH HEIGHTS.xlsx': ['Old', 'Until August'],
 'Jumeirah Island.xlsx': ['Old'],
 'Jumeirah Park.xlsx': ['Old', 'Apr to Dec'],
 'JVC.xlsx': ['Old', 'Apr to Dec'],
 'JVT.xlsx': ['Old', 'Apr to Dec'],
 'Lakes.xlsx': ['Old', 'Until August'],
 'Marina Dubai.xlsx': ['Old1', 'Apr to Dec'],
 'Marsa Dubai 2024.xlsx': ['Old1', 'Apr to Dec'],
 'Meydan District Data Copy.xlsx': ['Old', 'Sheet1', 'Until August', 'Sheet2'],
 'Meydan District.xlsx': ['Old', 'Until August'],
 'Mira - Mira Oasis.xlsx': ['Old', 'Apr to Dec1'],
 'MJL.xlsx': ['Old', 'Apr to Dec1'],
 'Motor City New.xlsx': ['Old', 'Apr to Dec'],
 'Nad al Shiba.xlsx': ['Old', 'Apr to Dec'],
 'Palm Jumeirah.xlsx': ['Old1', 'Apr to Dec1'],
 'Port De Lamer.xlsx': ['Old', 'Apr To Oct1', 'Nov To Dec1'],
 'Tilal Al Ghaf  New.xlsx': ['AURA',
  'Elan',
  'HARMONY',
  'ALAYA',
  'ELYSIAN',
  'TAG OLD',
  'SEP- Dec'],
 'Town Square.xlsx': ['Old', 'Apr to Dec'],
 'Victory Heights.xlsx': ['Old', 'Apr to Dec']}

In [6]:
sheet_availability = pd.DataFrame([available_sheets]).T.reset_index()
sheet_availability.columns = ['file_name', 'sheets']

In [7]:
sheet_availability

,file_name,sheets
0,Al Barari.xlsx,"[Old, Apr to Dec]"
1,"Arabian Ranches 1,2,3.xlsx","[Old, Apr to Dec]"
2,Arjan.xlsx,"[Old, Apr to Dec]"
3,Bluewater.xlsx,"[Old, Apr to Dec]"
4,Business Bay-1.xlsx,"[Old, Apr to Dec1]"
5,City Walk.xlsx,"[Old, Apr to Dec]"
6,Damac Hills 1.xlsx,"[Old, Apr to Dec1]"
7,Damac Hills 2.xlsx,"[Old, Apr to Dec]"
8,Damac Lagoon.xlsx,"[Old, Apr to Dec]"
9,Deira Island 2025.xlsx,"[Deira Island, Bay Villas]"
10,"Downtown Views T1, T2 and T3.xlsx","[Downtown Veiws (c), Sheet2, Sheet3]"
11,Downtown.xlsx,"[Old, Apr to Dec1]"
12,Dubai Creek Harbour.xlsx,"[Old, Apr to Dec]"
13,Dubai Hills.xlsx,"[Old1, Apr to Dec]"
14,Dubai South.xlsx,"[Old, Apr to Dec1]"
15,Emaar BeachFront.xlsx,"[Old, Apr to Dec]"
16,Emaar South.xlsx,"[Old, Apr to Dec]"
17,Emirates Living Nov 1.xlsx,"[Old1, Apr to Dec1]"
18,Furjan.xlsx,"[Old1, Apr to Dec1]"
19,Greens.xlsx,"[Old, Apr to Dec]"
20,JBR 2022.xlsx,"[Sheet1, Sheet2, Sheet3]"
21,JBR.xlsx,"[Old, Apr to Dec]"
22,JGE.xlsx,"[Old, Apr to Dec1]"
23,JLT.xlsx,"[Old, Apr to Dec1]"
24,Jumeirah Bay.xlsx,"[Old, Apr to Dec1]"
25,JUMEIRAH HEIGHTS.xlsx,"[Old, Until August]"
26,Jumeirah Island.xlsx,[Old]
27,Jumeirah Park.xlsx,"[Old, Apr to Dec]"
28,JVC.xlsx,"[Old, Apr to Dec]"
29,JVT.xlsx,"[Old, Apr to Dec]"
30,Lakes.xlsx,"[Old, Until August]"
31,Marina Dubai.xlsx,"[Old1, Apr to Dec]"
32,Marsa Dubai 2024.xlsx,"[Old1, Apr to Dec]"
33,Meydan District Data Copy.xlsx,"[Old, Sheet1, Until August, Sheet2]"
34,Meydan District.xlsx,"[Old, Until August]"
35,Mira - Mira Oasis.xlsx,"[Old, Apr to Dec1]"
36,MJL.xlsx,"[Old, Apr to Dec1]"
37,Motor City New.xlsx,"[Old, Apr to Dec]"
38,Nad al Shiba.xlsx,"[Old, Apr to Dec]"
39,Palm Jumeirah.xlsx,"[Old1, Apr to Dec1]"
40,Port De Lamer.xlsx,"[Old, Apr To Oct1, Nov To Dec1]"
41,Tilal Al Ghaf New.xlsx,"[AURA, Elan, HARMONY, ALAYA, ELYSIAN, TAG OLD,..."
42,Town Square.xlsx,"[Old, Apr to Dec]"
43,Victory Heights.xlsx,"[Old, Apr to Dec]"

In [21]:
sheet_availability = sheet_availability[
    sheet_availability['sheets'].apply(lambda x: len(x) == 2)
    & sheet_availability['sheets'].apply(lambda x: 'apr' in str(x).lower())
    & sheet_availability['sheets'].apply(lambda x: 'dec' in str(x).lower())
]

In [22]:
sheet_availability

                     file_name               sheets first_sheet second_sheet
0               Al Barari.xlsx    [Old, Apr to Dec]         Old   Apr to Dec
1   Arabian Ranches 1,2,3.xlsx    [Old, Apr to Dec]         Old   Apr to Dec
2                   Arjan.xlsx    [Old, Apr to Dec]         Old   Apr to Dec
3               Bluewater.xlsx    [Old, Apr to Dec]         Old   Apr to Dec
4          Business Bay-1.xlsx   [Old, Apr to Dec1]         Old  Apr to Dec1
5               City Walk.xlsx    [Old, Apr to Dec]         Old   Apr to Dec
6           Damac Hills 1.xlsx   [Old, Apr to Dec1]         Old  Apr to Dec1
7           Damac Hills 2.xlsx    [Old, Apr to Dec]         Old   Apr to Dec
8            Damac Lagoon.xlsx    [Old, Apr to Dec]         Old   Apr to Dec
11               Downtown.xlsx   [Old, Apr to Dec1]         Old  Apr to Dec1
12    Dubai Creek Harbour.xlsx    [Old, Apr to Dec]         Old   Apr to Dec
13            Dubai Hills.xlsx   [Old1, Apr to Dec]        Old1   Apr to Dec
14            Dubai South.xlsx   [Old, Apr to Dec1]         Old  Apr to Dec1
15       Emaar BeachFront.xlsx    [Old, Apr to Dec]         Old   Apr to Dec
16            Emaar South.xlsx    [Old, Apr to Dec]         Old   Apr to Dec
17  Emirates Living Nov 1.xlsx  [Old1, Apr to Dec1]        Old1  Apr to Dec1
18                 Furjan.xlsx  [Old1, Apr to Dec1]        Old1  Apr to Dec1
19                 Greens.xlsx    [Old, Apr to Dec]         Old   Apr to Dec
21                    JBR.xlsx    [Old, Apr to Dec]         Old   Apr to Dec
22                    JGE.xlsx   [Old, Apr to Dec1]         Old  Apr to Dec1
23                    JLT.xlsx   [Old, Apr to Dec1]         Old  Apr to Dec1
24           Jumeirah Bay.xlsx   [Old, Apr to Dec1]         Old  Apr to Dec1
27          Jumeirah Park.xlsx    [Old, Apr to Dec]         Old   Apr to Dec
28                    JVC.xlsx    [Old, Apr to Dec]         Old   Apr to Dec
29                    JVT.xlsx    [Old, Apr to Dec]         Old   Apr to Dec
31           Marina Dubai.xlsx   [Old1, Apr to Dec]        Old1   Apr to Dec
32       Marsa Dubai 2024.xlsx   [Old1, Apr to Dec]        Old1   Apr to Dec
35      Mira - Mira Oasis.xlsx   [Old, Apr to Dec1]         Old  Apr to Dec1
36                    MJL.xlsx   [Old, Apr to Dec1]         Old  Apr to Dec1
37         Motor City New.xlsx    [Old, Apr to Dec]         Old   Apr to Dec
38           Nad al Shiba.xlsx    [Old, Apr to Dec]         Old   Apr to Dec
39          Palm Jumeirah.xlsx  [Old1, Apr to Dec1]        Old1  Apr to Dec1
42            Town Square.xlsx    [Old, Apr to Dec]         Old   Apr to Dec
43        Victory Heights.xlsx    [Old, Apr to Dec]         Old   Apr to Dec

In [23]:
sheet_availability.loc[:, 'first_sheet'] = sheet_availability['sheets'].apply(lambda x: x[0])
sheet_availability.loc[:, 'second_sheet'] = sheet_availability['sheets'].apply(lambda x: x[1])

In [24]:
sheet_availability

                     file_name               sheets first_sheet second_sheet
0               Al Barari.xlsx    [Old, Apr to Dec]         Old   Apr to Dec
1   Arabian Ranches 1,2,3.xlsx    [Old, Apr to Dec]         Old   Apr to Dec
2                   Arjan.xlsx    [Old, Apr to Dec]         Old   Apr to Dec
3               Bluewater.xlsx    [Old, Apr to Dec]         Old   Apr to Dec
4          Business Bay-1.xlsx   [Old, Apr to Dec1]         Old  Apr to Dec1
5               City Walk.xlsx    [Old, Apr to Dec]         Old   Apr to Dec
6           Damac Hills 1.xlsx   [Old, Apr to Dec1]         Old  Apr to Dec1
7           Damac Hills 2.xlsx    [Old, Apr to Dec]         Old   Apr to Dec
8            Damac Lagoon.xlsx    [Old, Apr to Dec]         Old   Apr to Dec
11               Downtown.xlsx   [Old, Apr to Dec1]         Old  Apr to Dec1
12    Dubai Creek Harbour.xlsx    [Old, Apr to Dec]         Old   Apr to Dec
13            Dubai Hills.xlsx   [Old1, Apr to Dec]        Old1   Apr to Dec
14            Dubai South.xlsx   [Old, Apr to Dec1]         Old  Apr to Dec1
15       Emaar BeachFront.xlsx    [Old, Apr to Dec]         Old   Apr to Dec
16            Emaar South.xlsx    [Old, Apr to Dec]         Old   Apr to Dec
17  Emirates Living Nov 1.xlsx  [Old1, Apr to Dec1]        Old1  Apr to Dec1
18                 Furjan.xlsx  [Old1, Apr to Dec1]        Old1  Apr to Dec1
19                 Greens.xlsx    [Old, Apr to Dec]         Old   Apr to Dec
21                    JBR.xlsx    [Old, Apr to Dec]         Old   Apr to Dec
22                    JGE.xlsx   [Old, Apr to Dec1]         Old  Apr to Dec1
23                    JLT.xlsx   [Old, Apr to Dec1]         Old  Apr to Dec1
24           Jumeirah Bay.xlsx   [Old, Apr to Dec1]         Old  Apr to Dec1
27          Jumeirah Park.xlsx    [Old, Apr to Dec]         Old   Apr to Dec
28                    JVC.xlsx    [Old, Apr to Dec]         Old   Apr to Dec
29                    JVT.xlsx    [Old, Apr to Dec]         Old   Apr to Dec
31           Marina Dubai.xlsx   [Old1, Apr to Dec]        Old1   Apr to Dec
32       Marsa Dubai 2024.xlsx   [Old1, Apr to Dec]        Old1   Apr to Dec
35      Mira - Mira Oasis.xlsx   [Old, Apr to Dec1]         Old  Apr to Dec1
36                    MJL.xlsx   [Old, Apr to Dec1]         Old  Apr to Dec1
37         Motor City New.xlsx    [Old, Apr to Dec]         Old   Apr to Dec
38           Nad al Shiba.xlsx    [Old, Apr to Dec]         Old   Apr to Dec
39          Palm Jumeirah.xlsx  [Old1, Apr to Dec1]        Old1  Apr to Dec1
42            Town Square.xlsx    [Old, Apr to Dec]         Old   Apr to Dec
43        Victory Heights.xlsx    [Old, Apr to Dec]         Old   Apr to Dec

In [25]:
all_s1_data = []
base_path = '../data/owner_data'
for file, sheet in zip(sheet_availability.loc[:, 'file_name'], sheet_availability.loc[:, 'second_sheet']):
	file_path = os.path.join(base_path, file)
	data = pd.read_excel(file_path, sheet_name=sheet)
	data['file_name'] = file
	all_s1_data.append(data)

In [26]:
len(all_s1_data)

34

In [27]:
import pandas as pd

# Concatenate all dataframes, keeping all columns (union)
final_df = pd.concat(all_s1_data, ignore_index=True, sort=False)

# Check result
print(final_df.shape)
display(final_df.head())

(79209, 41)

,Transaction Date,Master Location,Master Project,Project,Building 1,BuildingName 2,property_number,UnitNumber,Completion Status,Property Type,Usage,beds,Sub Type,Transaction Amount,Actual Size,Plot Size,Built Up,Size,Municipality No,Municipality Sub No,LandNumber,Owner Name,Phone 1,Phone 2,Mobile 1,Mobile 2,file_name,Date,Secondary Mobile,property_completion_status_sk,bayut_property_type_name_en,property_usage_name_en,property_subtype_sk,transaction_amount,actual_area_sqm,plot_area_sqm,builtup_area_sqm,AreaMuncipalityNumber,LandMuncipalityNumber,Passport,Master Projects
0,2024-04-02,Al Barari,The Neighbourhood,The Neighbourhood C2,The Neighbourhood C2,C2,C246,C246,ready,Apartments,Residential,1,flat,1750000.0,76.76,NaN,76.76,76.76,645.0,5911.0,535.0,ABHISHEK MISHRA RAKESH KUMAR MISHRA,NaN,971|50-3600758,971|568677777,971|568677777,Al Barari.xlsx,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024-04-03,Al Barari,The Neighbourhood,The Neighbourhood C2,The Neighbourhood C2,C2,C244,C244,ready,Apartments,Residential,0,flat,1112500.0,47.76,NaN,47.76,47.76,645.0,5911.0,535.0,LENKA MAREKOVA,NaN,971|58-5120165,NaN,NaN,Al Barari.xlsx,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2024-04-04,Al Barari,The Neighbourhood,The Neighbourhood C2,The Neighbourhood C2,C2,C223,C223,ready,Apartments,Residential,1,flat,2450000.0,104.46,NaN,104.46,104.46,645.0,5911.0,535.0,SIEGFRIED KMIECIAK,NaN,971|54-3567750,971|543567750,971|543567750,Al Barari.xlsx,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2024-04-06,Al Barari,The Residences,Desert Leaf,Desert Leaf 5,16-09,16-09,NaN,ready,Villas,Residential,5,villa,23000000.0,1106.48,1106.48,1288.00,0.00,645.0,5460.0,67.0,Steven Sass,NaN,971|50-9162534,NaN,NaN,Al Barari.xlsx,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2024-04-26,Al Barari,Ixora,NaN,Ixora,BA-R-173,BA-R-173,NaN,off-plan,Villas,Residential,4,villa,6200000.0,180.29,180.29,458.96,0.00,645.0,5015.0,3538.0,zzzzzz,NaN,NaN,NaN,NaN,Al Barari.xlsx,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
missing_data = (final_df.isna().mean() * 100).reset_index()
missing_data.columns = ['Column Name', 'Missing %']
missing_data['Available In'] = np.nan
# missing_data = missing_data.set_index('Column Name')

In [29]:
# Initialize mapping dictionary
column_source_map = {}

# Loop over all columns in final_df
for col in final_df.columns:
	# Find which DataFrames contain this column
	sources = [(i, all_s1_data[i]['file_name'].iloc[0]) for i, df in enumerate(all_s1_data) if col in df.columns]
	column_source_map[col] = sources
	missing_data.loc[missing_data['Column Name'] == col, 'Available In'] = str(sources)

# Example: check mapping for a few columns
for k, v in list(column_source_map.items()):
	print(f"{k}: from DataFrames {v}")

Transaction Date: from DataFrames [(0, 'Al Barari.xlsx')]
Master Location: from DataFrames [(0, 'Al Barari.xlsx'), (1, 'Arabian Ranches 1,2,3.xlsx'), (2, 'Arjan.xlsx'), (3, 'Bluewater.xlsx'), (4, 'Business Bay-1.xlsx'), (5, 'City Walk.xlsx'), (6, 'Damac Hills 1.xlsx'), (7, 'Damac Hills 2.xlsx'), (8, 'Damac Lagoon.xlsx'), (9, 'Downtown.xlsx'), (10, 'Dubai Creek Harbour.xlsx'), (11, 'Dubai Hills.xlsx'), (12, 'Dubai South.xlsx'), (13, 'Emaar BeachFront.xlsx'), (14, 'Emaar South.xlsx'), (15, 'Emirates Living Nov 1.xlsx'), (16, 'Furjan.xlsx'), (17, 'Greens.xlsx'), (18, 'JBR.xlsx'), (19, 'JGE.xlsx'), (20, 'JLT.xlsx'), (21, 'Jumeirah Bay.xlsx'), (22, 'Jumeirah Park.xlsx'), (23, 'JVC.xlsx'), (24, 'JVT.xlsx'), (25, 'Marina Dubai.xlsx'), (26, 'Marsa Dubai 2024.xlsx'), (27, 'Mira - Mira Oasis.xlsx'), (29, 'Motor City New.xlsx'), (30, 'Nad al Shiba.xlsx'), (31, 'Palm Jumeirah.xlsx'), (32, 'Town Square.xlsx'), (33, 'Victory Heights.xlsx')]
Master Project: from DataFrames [(0, 'Al Barari.xlsx'), (1, 'Arabian Ranches 1,2,3.xlsx'), (2, 'Arjan.xlsx'), (3, 'Bluewater.xlsx'), (4, 'Business Bay-1.xlsx'), (5, 'City Walk.xlsx'), (6, 'Damac Hills 1.xlsx'), (7, 'Damac Hills 2.xlsx'), (8, 'Damac Lagoon.xlsx'), (9, 'Downtown.xlsx'), (11, 'Dubai Hills.xlsx'), (12, 'Dubai South.xlsx'), (13, 'Emaar BeachFront.xlsx'), (14, 'Emaar South.xlsx'), (15, 'Emirates Living Nov 1.xlsx'), (16, 'Furjan.xlsx'), (17, 'Greens.xlsx'), (18, 'JBR.xlsx'), (19, 'JGE.xlsx'), (20, 'JLT.xlsx'), (21, 'Jumeirah Bay.xlsx'), (22, 'Jumeirah Park.xlsx'), (23, 'JVC.xlsx'), (24, 'JVT.xlsx'), (25, 'Marina Dubai.xlsx'), (26, 'Marsa Dubai 2024.xlsx'), (27, 'Mira - Mira Oasis.xlsx'), (28, 'MJL.xlsx'), (29, 'Motor City New.xlsx'), (30, 'Nad al Shiba.xlsx'), (31, 'Palm Jumeirah.xlsx'), (32, 'Town Square.xlsx'), (33, 'Victory Heights.xlsx')]
Project: from DataFrames [(0, 'Al Barari.xlsx'), (1, 'Arabian Ranches 1,2,3.xlsx'), (2, 'Arjan.xlsx'), (3, 'Bluewater.xlsx'), (4, 'Business Bay-1.xlsx'), (5, 'City Walk.xlsx'), (6, 'Damac Hills 1.xlsx'), (7, 'Damac Hills 2.xlsx'), (8, 'Damac Lagoon.xlsx'), (9, 'Downtown.xlsx'), (10, 'Dubai Creek Harbour.xlsx'), (11, 'Dubai Hills.xlsx'), (12, 'Dubai South.xlsx'), (13, 'Emaar BeachFront.xlsx'), (14, 'Emaar South.xlsx'), (15, 'Emirates Living Nov 1.xlsx'), (16, 'Furjan.xlsx'), (17, 'Greens.xlsx'), (18, 'JBR.xlsx'), (19, 'JGE.xlsx'), (20, 'JLT.xlsx'), (21, 'Jumeirah Bay.xlsx'), (22, 'Jumeirah Park.xlsx'), (23, 'JVC.xlsx'), (24, 'JVT.xlsx'), (25, 'Marina Dubai.xlsx'), (26, 'Marsa Dubai 2024.xlsx'), (27, 'Mira - Mira Oasis.xlsx'), (28, 'MJL.xlsx'), (29, 'Motor City New.xlsx'), (30, 'Nad al Shiba.xlsx'), (31, 'Palm Jumeirah.xlsx'), (32, 'Town Square.xlsx'), (33, 'Victory Heights.xlsx')]
Building 1: from DataFrames [(0, 'Al Barari.xlsx'), (1, 'Arabian Ranches 1,2,3.xlsx'), (2, 'Arjan.xlsx'), (3, 'Bluewater.xlsx'), (4, 'Business Bay-1.xlsx'), (5, 'City Walk.xlsx'), (6, 'Damac Hills 1.xlsx'), (7, 'Damac Hills 2.xlsx'), (8, 'Damac Lagoon.xlsx'), (9, 'Downtown.xlsx'), (10, 'Dubai Creek Harbour.xlsx'), (11, 'Dubai Hills.xlsx'), (12, 'Dubai South.xlsx'), (13, 'Emaar BeachFront.xlsx'), (14, 'Emaar South.xlsx'), (15, 'Emirates Living Nov 1.xlsx'), (16, 'Furjan.xlsx'), (17, 'Greens.xlsx'), (18, 'JBR.xlsx'), (19, 'JGE.xlsx'), (20, 'JLT.xlsx'), (21, 'Jumeirah Bay.xlsx'), (22, 'Jumeirah Park.xlsx'), (23, 'JVC.xlsx'), (24, 'JVT.xlsx'), (25, 'Marina Dubai.xlsx'), (26, 'Marsa Dubai 2024.xlsx'), (27, 'Mira - Mira Oasis.xlsx'), (28, 'MJL.xlsx'), (29, 'Motor City New.xlsx'), (30, 'Nad al Shiba.xlsx'), (31, 'Palm Jumeirah.xlsx'), (32, 'Town Square.xlsx'), (33, 'Victory Heights.xlsx')]
BuildingName 2: from DataFrames [(0, 'Al Barari.xlsx'), (1, 'Arabian Ranches 1,2,3.xlsx'), (2, 'Arjan.xlsx'), (3, 'Bluewater.xlsx'), (4, 'Business Bay-1.xlsx'), (5, 'City Walk.xlsx'), (6, 'Damac Hills 1.xlsx'), (7, 'Damac Hills 2.xlsx'), (8, 'Damac Lagoon.xlsx'), (9, 'Downtown.xlsx'), (10, 'Dubai Creek Harbour.xlsx'), (11, 'Dubai Hills.xlsx'), (12, 'Dubai South.xlsx'), (13, 'Emaar BeachFront.xlsx'), (14, 'Emaar South.xlsx'), (15, 'Emirates Living Nov 1.xlsx'), (16, 'Furjan.xlsx'), (17, 'Greens.xlsx'), (18, 'JBR.xlsx'), (19, 'JGE.xlsx'), (20, 'JLT.xlsx'), (21, 'Jumeirah Bay.xlsx'), (22, 'Jumeirah Park.xlsx'), (23, 'JVC.xlsx'), (24, 'JVT.xlsx'), (25, 'Marina Dubai.xlsx'), (26, 'Marsa Dubai 2024.xlsx'), (27, 'Mira - Mira Oasis.xlsx'), (28, 'MJL.xlsx'), (29, 'Motor City New.xlsx'), (30, 'Nad al Shiba.xlsx'), (31, 'Palm Jumeirah.xlsx'), (32, 'Town Square.xlsx'), (33, 'Victory Heights.xlsx')]
property_number: from DataFrames [(0, 'Al Barari.xlsx'), (1, 'Arabian Ranches 1,2,3.xlsx'), (2, 'Arjan.xlsx'), (3, 'Bluewater.xlsx'), (4, 'Business Bay-1.xlsx'), (5, 'City Walk.xlsx'), (6, 'Damac Hills 1.xlsx'), (7, 'Damac Hills 2.xlsx'), (8, 'Damac Lagoon.xlsx'), (9, 'Downtown.xlsx'), (10, 'Dubai Creek Harbour.xlsx'), (11, 'Dubai Hills.xlsx'), (12, 'Dubai South.xlsx'), (13, 'Emaar BeachFront.xlsx'), (14, 'Emaar South.xlsx'), (15, 'Emirates Living Nov 1.xlsx'), (16, 'Furjan.xlsx'), (17, 'Greens.xlsx'), (18, 'JBR.xlsx'), (19, 'JGE.xlsx'), (20, 'JLT.xlsx'), (21, 'Jumeirah Bay.xlsx'), (22, 'Jumeirah Park.xlsx'), (23, 'JVC.xlsx'), (24, 'JVT.xlsx'), (25, 'Marina Dubai.xlsx'), (26, 'Marsa Dubai 2024.xlsx'), (27, 'Mira - Mira Oasis.xlsx'), (28, 'MJL.xlsx'), (29, 'Motor City New.xlsx'), (30, 'Nad al Shiba.xlsx'), (31, 'Palm Jumeirah.xlsx'), (32, 'Town Square.xlsx'), (33, 'Victory Heights.xlsx')]
UnitNumber: from DataFrames [(0, 'Al Barari.xlsx'), (2, 'Arjan.xlsx'), (3, 'Bluewater.xlsx'), (4, 'Business Bay-1.xlsx'), (5, 'City Walk.xlsx'), (6, 'Damac Hills 1.xlsx'), (7, 'Damac Hills 2.xlsx'), (8, 'Damac Lagoon.xlsx'), (9, 'Downtown.xlsx'), (10, 'Dubai Creek Harbour.xlsx'), (11, 'Dubai Hills.xlsx'), (12, 'Dubai South.xlsx'), (13, 'Emaar BeachFront.xlsx'), (14, 'Emaar South.xlsx'), (15, 'Emirates Living Nov 1.xlsx'), (16, 'Furjan.xlsx'), (17, 'Greens.xlsx'), (18, 'JBR.xlsx'), (19, 'JGE.xlsx'), (20, 'JLT.xlsx'), (21, 'Jumeirah Bay.xlsx'), (22, 'Jumeirah Park.xlsx'), (23, 'JVC.xlsx'), (24, 'JVT.xlsx'), (25, 'Marina Dubai.xlsx'), (26, 'Marsa Dubai 2024.xlsx'), (27, 'Mira - Mira Oasis.xlsx'), (28, 'MJL.xlsx'), (29, 'Motor City New.xlsx'), (30, 'Nad al Shiba.xlsx'), (31, 'Palm Jumeirah.xlsx'), (32, 'Town Square.xlsx'), (33, 'Victory Heights.xlsx')]
Completion Status: from DataFrames [(0, 'Al Barari.xlsx'), (1, 'Arabian Ranches 1,2,3.xlsx'), (2, 'Arjan.xlsx'), (3, 'Bluewater.xlsx'), (5, 'City Walk.xlsx'), (6, 'Damac Hills 1.xlsx'), (7, 'Damac Hills 2.xlsx'), (8, 'Damac Lagoon.xlsx'), (9, 'Downtown.xlsx'), (10, 'Dubai Creek Harbour.xlsx'), (11, 'Dubai Hills.xlsx'), (12, 'Dubai South.xlsx'), (13, 'Emaar BeachFront.xlsx'), (14, 'Emaar South.xlsx'), (15, 'Emirates Living Nov 1.xlsx'), (16, 'Furjan.xlsx'), (17, 'Greens.xlsx'), (18, 'JBR.xlsx'), (19, 'JGE.xlsx'), (20, 'JLT.xlsx'), (21, 'Jumeirah Bay.xlsx'), (22, 'Jumeirah Park.xlsx'), (23, 'JVC.xlsx'), (24, 'JVT.xlsx'), (25, 'Marina Dubai.xlsx'), (26, 'Marsa Dubai 2024.xlsx'), (27, 'Mira - Mira Oasis.xlsx'), (28, 'MJL.xlsx'), (29, 'Motor City New.xlsx'), (30, 'Nad al Shiba.xlsx'), (31, 'Palm Jumeirah.xlsx'), (32, 'Town Square.xlsx'), (33, 'Victory Heights.xlsx')]
Property Type: from DataFrames [(0, 'Al Barari.xlsx'), (1, 'Arabian Ranches 1,2,3.xlsx'), (2, 'Arjan.xlsx'), (3, 'Bluewater.xlsx'), (5, 'City Walk.xlsx'), (6, 'Damac Hills 1.xlsx'), (7, 'Damac Hills 2.xlsx'), (8, 'Damac Lagoon.xlsx'), (9, 'Downtown.xlsx'), (10, 'Dubai Creek Harbour.xlsx'), (11, 'Dubai Hills.xlsx'), (12, 'Dubai South.xlsx'), (13, 'Emaar BeachFront.xlsx'), (14, 'Emaar South.xlsx'), (15, 'Emirates Living Nov 1.xlsx'), (16, 'Furjan.xlsx'), (17, 'Greens.xlsx'), (18, 'JBR.xlsx'), (19, 'JGE.xlsx'), (20, 'JLT.xlsx'), (21, 'Jumeirah Bay.xlsx'), (22, 'Jumeirah Park.xlsx'), (23, 'JVC.xlsx'), (24, 'JVT.xlsx'), (25, 'Marina Dubai.xlsx'), (26, 'Marsa Dubai 2024.xlsx'), (27, 'Mira - Mira Oasis.xlsx'), (28, 'MJL.xlsx'), (29, 'Motor City New.xlsx'), (30, 'Nad al Shiba.xlsx'), (31, 'Palm Jumeirah.xlsx'), (32, 'Town Square.xlsx'), (33, 'Victory Heights.xlsx')]
Usage: from DataFrames [(0, 'Al Barari.xlsx'), (1, 'Arabian Ranches 1,2,3.xlsx'), (2, 'Arjan.xlsx'), (3, 'Bluewater.xlsx'), (5, 'City Walk.xlsx'), (6, 'Damac Hills 1.xlsx'), (7, 'Damac Hills 2.xlsx'), (8, 'Damac Lagoon.xlsx'), (9, 'Downtown.xlsx'), (10, 'Dubai Creek Harbour.xlsx'), (11, 'Dubai Hills.xlsx'), (12, 'Dubai South.xlsx'), (13, 'Emaar BeachFront.xlsx'), (14, 'Emaar South.xlsx'), (15, 'Emirates Living Nov 1.xlsx'), (16, 'Furjan.xlsx'), (17, 'Greens.xlsx'), (18, 'JBR.xlsx'), (19, 'JGE.xlsx'), (20, 'JLT.xlsx'), (21, 'Jumeirah Bay.xlsx'), (22, 'Jumeirah Park.xlsx'), (23, 'JVC.xlsx'), (24, 'JVT.xlsx'), (25, 'Marina Dubai.xlsx'), (26, 'Marsa Dubai 2024.xlsx'), (27, 'Mira - Mira Oasis.xlsx'), (28, 'MJL.xlsx'), (29, 'Motor City New.xlsx'), (30, 'Nad al Shiba.xlsx'), (31, 'Palm Jumeirah.xlsx'), (32, 'Town Square.xlsx'), (33, 'Victory Heights.xlsx')]
beds: from DataFrames [(0, 'Al Barari.xlsx'), (1, 'Arabian Ranches 1,2,3.xlsx'), (2, 'Arjan.xlsx'), (3, 'Bluewater.xlsx'), (4, 'Business Bay-1.xlsx'), (5, 'City Walk.xlsx'), (6, 'Damac Hills 1.xlsx'), (7, 'Damac Hills 2.xlsx'), (8, 'Damac Lagoon.xlsx'), (9, 'Downtown.xlsx'), (10, 'Dubai Creek Harbour.xlsx'), (11, 'Dubai Hills.xlsx'), (12, 'Dubai South.xlsx'), (13, 'Emaar BeachFront.xlsx'), (14, 'Emaar South.xlsx'), (15, 'Emirates Living Nov 1.xlsx'), (16, 'Furjan.xlsx'), (17, 'Greens.xlsx'), (18, 'JBR.xlsx'), (19, 'JGE.xlsx'), (20, 'JLT.xlsx'), (21, 'Jumeirah Bay.xlsx'), (22, 'Jumeirah Park.xlsx'), (23, 'JVC.xlsx'), (24, 'JVT.xlsx'), (25, 'Marina Dubai.xlsx'), (26, 'Marsa Dubai 2024.xlsx'), (27, 'Mira - Mira Oasis.xlsx'), (28, 'MJL.xlsx'), (29, 'Motor City New.xlsx'), (30, 'Nad al Shiba.xlsx'), (31, 'Palm Jumeirah.xlsx'), (32, 'Town Square.xlsx'), (33, 'Victory Heights.xlsx')]
Sub Type: from DataFrames [(0, 'Al Barari.xlsx'), (1, 'Arabian Ranches 1,2,3.xlsx'), (2, 'Arjan.xlsx'), (3, 'Bluewater.xlsx'), (5, 'City Walk.xlsx'), (6, 'Damac Hills 1.xlsx'), (7, 'Damac Hills 2.xlsx'), (8, 'Damac Lagoon.xlsx'), (9, 'Downtown.xlsx'), (10, 'Dubai Creek Harbour.xlsx'), (11, 'Dubai Hills.xlsx'), (12, 'Dubai South.xlsx'), (13, 'Emaar BeachFront.xlsx'), (14, 'Emaar South.xlsx'), (15, 'Emirates Living Nov 1.xlsx'), (16, 'Furjan.xlsx'), (17, 'Greens.xlsx'), (18, 'JBR.xlsx'), (19, 'JGE.xlsx'), (20, 'JLT.xlsx'), (21, 'Jumeirah Bay.xlsx'), (22, 'Jumeirah Park.xlsx'), (23, 'JVC.xlsx'), (25, 'Marina Dubai.xlsx'), (26, 'Marsa Dubai 2024.xlsx'), (27, 'Mira - Mira Oasis.xlsx'), (28, 'MJL.xlsx'), (29, 'Motor City New.xlsx'), (30, 'Nad al Shiba.xlsx'), (31, 'Palm Jumeirah.xlsx'), (32, 'Town Square.xlsx'), (33, 'Victory Heights.xlsx')]
Transaction Amount: from DataFrames [(0, 'Al Barari.xlsx'), (1, 'Arabian Ranches 1,2,3.xlsx'), (2, 'Arjan.xlsx'), (3, 'Bluewater.xlsx'), (5, 'City Walk.xlsx'), (6, 'Damac Hills 1.xlsx'), (7, 'Damac Hills 2.xlsx'), (8, 'Damac Lagoon.xlsx'), (9, 'Downtown.xlsx'), (10, 'Dubai Creek Harbour.xlsx'), (11, 'Dubai Hills.xlsx'), (12, 'Dubai South.xlsx'), (13, 'Emaar BeachFront.xlsx'), (14, 'Emaar South.xlsx'), (15, 'Emirates Living Nov 1.xlsx'), (16, 'Furjan.xlsx'), (17, 'Greens.xlsx'), (18, 'JBR.xlsx'), (19, 'JGE.xlsx'), (20, 'JLT.xlsx'), (21, 'Jumeirah Bay.xlsx'), (22, 'Jumeirah Park.xlsx'), (23, 'JVC.xlsx'), (25, 'Marina Dubai.xlsx'), (26, 'Marsa Dubai 2024.xlsx'), (27, 'Mira - Mira Oasis.xlsx'), (28, 'MJL.xlsx'), (29, 'Motor City New.xlsx'), (30, 'Nad al Shiba.xlsx'), (31, 'Palm Jumeirah.xlsx'), (32, 'Town Square.xlsx'), (33, 'Victory Heights.xlsx')]
Actual Size: from DataFrames [(0, 'Al Barari.xlsx'), (1, 'Arabian Ranches 1,2,3.xlsx'), (2, 'Arjan.xlsx'), (3, 'Bluewater.xlsx'), (5, 'City Walk.xlsx'), (6, 'Damac Hills 1.xlsx'), (7, 'Damac Hills 2.xlsx'), (8, 'Damac Lagoon.xlsx'), (9, 'Downtown.xlsx'), (10, 'Dubai Creek Harbour.xlsx'), (11, 'Dubai Hills.xlsx'), (12, 'Dubai South.xlsx'), (13, 'Emaar BeachFront.xlsx'), (14, 'Emaar South.xlsx'), (15, 'Emirates Living Nov 1.xlsx'), (16, 'Furjan.xlsx'), (17, 'Greens.xlsx'), (18, 'JBR.xlsx'), (19, 'JGE.xlsx'), (20, 'JLT.xlsx'), (21, 'Jumeirah Bay.xlsx'), (22, 'Jumeirah Park.xlsx'), (23, 'JVC.xlsx'), (25, 'Marina Dubai.xlsx'), (26, 'Marsa Dubai 2024.xlsx'), (27, 'Mira - Mira Oasis.xlsx'), (28, 'MJL.xlsx'), (29, 'Motor City New.xlsx'), (30, 'Nad al Shiba.xlsx'), (31, 'Palm Jumeirah.xlsx'), (32, 'Town Square.xlsx'), (33, 'Victory Heights.xlsx')]
Plot Size: from DataFrames [(0, 'Al Barari.xlsx'), (1, 'Arabian Ranches 1,2,3.xlsx'), (2, 'Arjan.xlsx'), (3, 'Bluewater.xlsx'), (5, 'City Walk.xlsx'), (6, 'Damac Hills 1.xlsx'), (7, 'Damac Hills 2.xlsx'), (8, 'Damac Lagoon.xlsx'), (9, 'Downtown.xlsx'), (10, 'Dubai Creek Harbour.xlsx'), (11, 'Dubai Hills.xlsx'), (12, 'Dubai South.xlsx'), (13, 'Emaar BeachFront.xlsx'), (14, 'Emaar South.xlsx'), (15, 'Emirates Living Nov 1.xlsx'), (16, 'Furjan.xlsx'), (17, 'Greens.xlsx'), (18, 'JBR.xlsx'), (19, 'JGE.xlsx'), (20, 'JLT.xlsx'), (21, 'Jumeirah Bay.xlsx'), (22, 'Jumeirah Park.xlsx'), (23, 'JVC.xlsx'), (25, 'Marina Dubai.xlsx'), (26, 'Marsa Dubai 2024.xlsx'), (27, 'Mira - Mira Oasis.xlsx'), (28, 'MJL.xlsx'), (29, 'Motor City New.xlsx'), (30, 'Nad al Shiba.xlsx'), (31, 'Palm Jumeirah.xlsx'), (32, 'Town Square.xlsx'), (33, 'Victory Heights.xlsx')]
Built Up: from DataFrames [(0, 'Al Barari.xlsx'), (1, 'Arabian Ranches 1,2,3.xlsx'), (2, 'Arjan.xlsx'), (3, 'Bluewater.xlsx'), (5, 'City Walk.xlsx'), (6, 'Damac Hills 1.xlsx'), (7, 'Damac Hills 2.xlsx'), (8, 'Damac Lagoon.xlsx'), (9, 'Downtown.xlsx'), (10, 'Dubai Creek Harbour.xlsx'), (11, 'Dubai Hills.xlsx'), (12, 'Dubai South.xlsx'), (13, 'Emaar BeachFront.xlsx'), (14, 'Emaar South.xlsx'), (15, 'Emirates Living Nov 1.xlsx'), (16, 'Furjan.xlsx'), (17, 'Greens.xlsx'), (18, 'JBR.xlsx'), (19, 'JGE.xlsx'), (20, 'JLT.xlsx'), (21, 'Jumeirah Bay.xlsx'), (22, 'Jumeirah Park.xlsx'), (23, 'JVC.xlsx'), (25, 'Marina Dubai.xlsx'), (26, 'Marsa Dubai 2024.xlsx'), (27, 'Mira - Mira Oasis.xlsx'), (28, 'MJL.xlsx'), (29, 'Motor City New.xlsx'), (30, 'Nad al Shiba.xlsx'), (31, 'Palm Jumeirah.xlsx'), (32, 'Town Square.xlsx'), (33, 'Victory Heights.xlsx')]
Size: from DataFrames [(0, 'Al Barari.xlsx'), (2, 'Arjan.xlsx'), (3, 'Bluewater.xlsx'), (4, 'Business Bay-1.xlsx'), (5, 'City Walk.xlsx'), (6, 'Damac Hills 1.xlsx'), (7, 'Damac Hills 2.xlsx'), (8, 'Damac Lagoon.xlsx'), (9, 'Downtown.xlsx'), (10, 'Dubai Creek Harbour.xlsx'), (11, 'Dubai Hills.xlsx'), (12, 'Dubai South.xlsx'), (13, 'Emaar BeachFront.xlsx'), (14, 'Emaar South.xlsx'), (15, 'Emirates Living Nov 1.xlsx'), (16, 'Furjan.xlsx'), (17, 'Greens.xlsx'), (18, 'JBR.xlsx'), (19, 'JGE.xlsx'), (20, 'JLT.xlsx'), (21, 'Jumeirah Bay.xlsx'), (22, 'Jumeirah Park.xlsx'), (23, 'JVC.xlsx'), (24, 'JVT.xlsx'), (25, 'Marina Dubai.xlsx'), (26, 'Marsa Dubai 2024.xlsx'), (27, 'Mira - Mira Oasis.xlsx'), (28, 'MJL.xlsx'), (29, 'Motor City New.xlsx'), (30, 'Nad al Shiba.xlsx'), (31, 'Palm Jumeirah.xlsx'), (32, 'Town Square.xlsx'), (33, 'Victory Heights.xlsx')]
Municipality No: from DataFrames [(0, 'Al Barari.xlsx'), (1, 'Arabian Ranches 1,2,3.xlsx'), (2, 'Arjan.xlsx'), (3, 'Bluewater.xlsx'), (5, 'City Walk.xlsx'), (6, 'Damac Hills 1.xlsx'), (7, 'Damac Hills 2.xlsx'), (8, 'Damac Lagoon.xlsx'), (9, 'Downtown.xlsx'), (10, 'Dubai Creek Harbour.xlsx'), (11, 'Dubai Hills.xlsx'), (12, 'Dubai South.xlsx'), (13, 'Emaar BeachFront.xlsx'), (14, 'Emaar South.xlsx'), (15, 'Emirates Living Nov 1.xlsx'), (16, 'Furjan.xlsx'), (17, 'Greens.xlsx'), (18, 'JBR.xlsx'), (19, 'JGE.xlsx'), (20, 'JLT.xlsx'), (21, 'Jumeirah Bay.xlsx'), (22, 'Jumeirah Park.xlsx'), (23, 'JVC.xlsx'), (25, 'Marina Dubai.xlsx'), (26, 'Marsa Dubai 2024.xlsx'), (27, 'Mira - Mira Oasis.xlsx'), (28, 'MJL.xlsx'), (29, 'Motor City New.xlsx'), (30, 'Nad al Shiba.xlsx'), (31, 'Palm Jumeirah.xlsx'), (32, 'Town Square.xlsx'), (33, 'Victory Heights.xlsx')]
Municipality Sub No: from DataFrames [(0, 'Al Barari.xlsx'), (1, 'Arabian Ranches 1,2,3.xlsx'), (2, 'Arjan.xlsx'), (3, 'Bluewater.xlsx'), (5, 'City Walk.xlsx'), (6, 'Damac Hills 1.xlsx'), (7, 'Damac Hills 2.xlsx'), (8, 'Damac Lagoon.xlsx'), (9, 'Downtown.xlsx'), (10, 'Dubai Creek Harbour.xlsx'), (11, 'Dubai Hills.xlsx'), (12, 'Dubai South.xlsx'), (13, 'Emaar BeachFront.xlsx'), (14, 'Emaar South.xlsx'), (15, 'Emirates Living Nov 1.xlsx'), (16, 'Furjan.xlsx'), (17, 'Greens.xlsx'), (18, 'JBR.xlsx'), (19, 'JGE.xlsx'), (20, 'JLT.xlsx'), (21, 'Jumeirah Bay.xlsx'), (22, 'Jumeirah Park.xlsx'), (23, 'JVC.xlsx'), (25, 'Marina Dubai.xlsx'), (26, 'Marsa Dubai 2024.xlsx'), (27, 'Mira - Mira Oasis.xlsx'), (28, 'MJL.xlsx'), (29, 'Motor City New.xlsx'), (30, 'Nad al Shiba.xlsx'), (31, 'Palm Jumeirah.xlsx'), (32, 'Town Square.xlsx'), (33, 'Victory Heights.xlsx')]
LandNumber: from DataFrames [(0, 'Al Barari.xlsx'), (1, 'Arabian Ranches 1,2,3.xlsx'), (2, 'Arjan.xlsx'), (3, 'Bluewater.xlsx'), (4, 'Business Bay-1.xlsx'), (5, 'City Walk.xlsx'), (6, 'Damac Hills 1.xlsx'), (7, 'Damac Hills 2.xlsx'), (8, 'Damac Lagoon.xlsx'), (9, 'Downtown.xlsx'), (10, 'Dubai Creek Harbour.xlsx'), (11, 'Dubai Hills.xlsx'), (12, 'Dubai South.xlsx'), (13, 'Emaar BeachFront.xlsx'), (14, 'Emaar South.xlsx'), (15, 'Emirates Living Nov 1.xlsx'), (16, 'Furjan.xlsx'), (17, 'Greens.xlsx'), (18, 'JBR.xlsx'), (19, 'JGE.xlsx'), (20, 'JLT.xlsx'), (21, 'Jumeirah Bay.xlsx'), (22, 'Jumeirah Park.xlsx'), (23, 'JVC.xlsx'), (24, 'JVT.xlsx'), (25, 'Marina Dubai.xlsx'), (26, 'Marsa Dubai 2024.xlsx'), (27, 'Mira - Mira Oasis.xlsx'), (28, 'MJL.xlsx'), (29, 'Motor City New.xlsx'), (30, 'Nad al Shiba.xlsx'), (31, 'Palm Jumeirah.xlsx'), (32, 'Town Square.xlsx'), (33, 'Victory Heights.xlsx')]
Owner Name: from DataFrames [(0, 'Al Barari.xlsx'), (1, 'Arabian Ranches 1,2,3.xlsx'), (2, 'Arjan.xlsx'), (3, 'Bluewater.xlsx'), (4, 'Business Bay-1.xlsx'), (5, 'City Walk.xlsx'), (6, 'Damac Hills 1.xlsx'), (7, 'Damac Hills 2.xlsx'), (8, 'Damac Lagoon.xlsx'), (9, 'Downtown.xlsx'), (10, 'Dubai Creek Harbour.xlsx'), (11, 'Dubai Hills.xlsx'), (12, 'Dubai South.xlsx'), (13, 'Emaar BeachFront.xlsx'), (14, 'Emaar South.xlsx'), (15, 'Emirates Living Nov 1.xlsx'), (16, 'Furjan.xlsx'), (17, 'Greens.xlsx'), (18, 'JBR.xlsx'), (19, 'JGE.xlsx'), (20, 'JLT.xlsx'), (21, 'Jumeirah Bay.xlsx'), (22, 'Jumeirah Park.xlsx'), (23, 'JVC.xlsx'), (24, 'JVT.xlsx'), (25, 'Marina Dubai.xlsx'), (26, 'Marsa Dubai 2024.xlsx'), (27, 'Mira - Mira Oasis.xlsx'), (28, 'MJL.xlsx'), (29, 'Motor City New.xlsx'), (30, 'Nad al Shiba.xlsx'), (31, 'Palm Jumeirah.xlsx'), (32, 'Town Square.xlsx'), (33, 'Victory Heights.xlsx')]
Phone 1: from DataFrames [(0, 'Al Barari.xlsx'), (1, 'Arabian Ranches 1,2,3.xlsx'), (2, 'Arjan.xlsx'), (3, 'Bluewater.xlsx'), (4, 'Business Bay-1.xlsx'), (5, 'City Walk.xlsx'), (6, 'Damac Hills 1.xlsx'), (7, 'Damac Hills 2.xlsx'), (8, 'Damac Lagoon.xlsx'), (9, 'Downtown.xlsx'), (10, 'Dubai Creek Harbour.xlsx'), (11, 'Dubai Hills.xlsx'), (12, 'Dubai South.xlsx'), (13, 'Emaar BeachFront.xlsx'), (14, 'Emaar South.xlsx'), (15, 'Emirates Living Nov 1.xlsx'), (16, 'Furjan.xlsx'), (17, 'Greens.xlsx'), (18, 'JBR.xlsx'), (19, 'JGE.xlsx'), (20, 'JLT.xlsx'), (21, 'Jumeirah Bay.xlsx'), (22, 'Jumeirah Park.xlsx'), (23, 'JVC.xlsx'), (24, 'JVT.xlsx'), (25, 'Marina Dubai.xlsx'), (26, 'Marsa Dubai 2024.xlsx'), (27, 'Mira - Mira Oasis.xlsx'), (28, 'MJL.xlsx'), (29, 'Motor City New.xlsx'), (30, 'Nad al Shiba.xlsx'), (31, 'Palm Jumeirah.xlsx'), (32, 'Town Square.xlsx'), (33, 'Victory Heights.xlsx')]

In [30]:
missing_data['Available In'] = missing_data['Available In'].apply(eval)
missing_data['Available Cnt'] = missing_data['Available In'].apply(lambda x: len(x))

In [31]:
# missing_data.to_csv('../data/missing_data_new.csv', index=False)

In [32]:
missing_data

,Column Name,Missing %,Available In,Available Cnt
0,Transaction Date,99.878802,"[(0, Al Barari.xlsx)]",1
1,Master Location,0.573167,"[(0, Al Barari.xlsx), (1, Arabian Ranches 1,2,...",33
2,Master Project,5.005744,"[(0, Al Barari.xlsx), (1, Arabian Ranches 1,2,...",33
3,Project,43.558182,"[(0, Al Barari.xlsx), (1, Arabian Ranches 1,2,...",34
4,Building 1,0.671641,"[(0, Al Barari.xlsx), (1, Arabian Ranches 1,2,...",34
5,BuildingName 2,25.094371,"[(0, Al Barari.xlsx), (1, Arabian Ranches 1,2,...",34
6,property_number,1.041548,"[(0, Al Barari.xlsx), (1, Arabian Ranches 1,2,...",34
7,UnitNumber,32.034239,"[(0, Al Barari.xlsx), (2, Arjan.xlsx), (3, Blu...",33
8,Completion Status,27.306240,"[(0, Al Barari.xlsx), (1, Arabian Ranches 1,2,...",33
9,Property Type,27.301191,"[(0, Al Barari.xlsx), (1, Arabian Ranches 1,2,...",33
10,Usage,27.301191,"[(0, Al Barari.xlsx), (1, Arabian Ranches 1,2,...",33
11,beds,4.460352,"[(0, Al Barari.xlsx), (1, Arabian Ranches 1,2,...",34
12,Sub Type,28.942418,"[(0, Al Barari.xlsx), (1, Arabian Ranches 1,2,...",32
13,Transaction Amount,29.362825,"[(0, Al Barari.xlsx), (1, Arabian Ranches 1,2,...",32
14,Actual Size,13.877211,"[(0, Al Barari.xlsx), (1, Arabian Ranches 1,2,...",32
15,Plot Size,88.784103,"[(0, Al Barari.xlsx), (1, Arabian Ranches 1,2,...",32
16,Built Up,30.408161,"[(0, Al Barari.xlsx), (1, Arabian Ranches 1,2,...",32
17,Size,21.858627,"[(0, Al Barari.xlsx), (2, Arjan.xlsx), (3, Blu...",33
18,Municipality No,18.953654,"[(0, Al Barari.xlsx), (1, Arabian Ranches 1,2,...",32
19,Municipality Sub No,19.129139,"[(0, Al Barari.xlsx), (1, Arabian Ranches 1,2,...",32
20,LandNumber,5.538512,"[(0, Al Barari.xlsx), (1, Arabian Ranches 1,2,...",34
21,Owner Name,9.245162,"[(0, Al Barari.xlsx), (1, Arabian Ranches 1,2,...",34
22,Phone 1,82.883258,"[(0, Al Barari.xlsx), (1, Arabian Ranches 1,2,...",34
23,Phone 2,39.732859,"[(0, Al Barari.xlsx), (1, Arabian Ranches 1,2,...",34
24,Mobile 1,73.188653,"[(0, Al Barari.xlsx), (1, Arabian Ranches 1,2,...",34
25,Mobile 2,55.564393,"[(0, Al Barari.xlsx), (1, Arabian Ranches 1,2,...",34
26,file_name,0.000000,"[(0, Al Barari.xlsx), (1, Arabian Ranches 1,2,...",34
27,Date,0.121198,"[(1, Arabian Ranches 1,2,3.xlsx), (2, Arjan.xl...",33
28,Secondary Mobile,89.143910,"[(1, Arabian Ranches 1,2,3.xlsx), (3, Bluewate...",32
29,property_completion_status_sk,91.694126,"[(4, Business Bay-1.xlsx)]",1
30,bayut_property_type_name_en,91.694126,"[(4, Business Bay-1.xlsx)]",1
31,property_usage_name_en,91.694126,"[(4, Business Bay-1.xlsx)]",1
32,property_subtype_sk,89.632491,"[(4, Business Bay-1.xlsx), (24, JVT.xlsx)]",2
33,transaction_amount,89.632491,"[(4, Business Bay-1.xlsx), (24, JVT.xlsx)]",2
34,actual_area_sqm,86.711106,"[(4, Business Bay-1.xlsx), (24, JVT.xlsx)]",2
35,plot_area_sqm,99.864914,"[(4, Business Bay-1.xlsx), (24, JVT.xlsx)]",2
36,builtup_area_sqm,89.665316,"[(4, Business Bay-1.xlsx), (24, JVT.xlsx)]",2
37,AreaMuncipalityNumber,86.924466,"[(4, Business Bay-1.xlsx), (24, JVT.xlsx)]",2
38,LandMuncipalityNumber,86.924466,"[(4, Business Bay-1.xlsx), (24, JVT.xlsx)]",2
39,Passport,77.180623,"[(7, Damac Hills 2.xlsx), (8, Damac Lagoon.xls...",22
40,Master Projects,95.621710,"[(10, Dubai Creek Harbour.xlsx)]",1

In [33]:
final_df

,Transaction Date,Master Location,Master Project,Project,Building 1,BuildingName 2,property_number,UnitNumber,Completion Status,Property Type,Usage,beds,Sub Type,Transaction Amount,Actual Size,Plot Size,Built Up,Size,Municipality No,Municipality Sub No,LandNumber,Owner Name,Phone 1,Phone 2,Mobile 1,Mobile 2,file_name,Date,Secondary Mobile,property_completion_status_sk,bayut_property_type_name_en,property_usage_name_en,property_subtype_sk,transaction_amount,actual_area_sqm,plot_area_sqm,builtup_area_sqm,AreaMuncipalityNumber,LandMuncipalityNumber,Passport,Master Projects
0,2024-04-02,Al Barari,The Neighbourhood,The Neighbourhood C2,The Neighbourhood C2,C2,C246,C246,ready,Apartments,Residential,1,flat,1750000.0,76.76,NaN,76.76,76.76,645.0,5911.0,535.0,ABHISHEK MISHRA RAKESH KUMAR MISHRA,NaN,971|50-3600758,971|568677777,971|568677777,Al Barari.xlsx,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024-04-03,Al Barari,The Neighbourhood,The Neighbourhood C2,The Neighbourhood C2,C2,C244,C244,ready,Apartments,Residential,0,flat,1112500.0,47.76,NaN,47.76,47.76,645.0,5911.0,535.0,LENKA MAREKOVA,NaN,971|58-5120165,NaN,NaN,Al Barari.xlsx,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2024-04-04,Al Barari,The Neighbourhood,The Neighbourhood C2,The Neighbourhood C2,C2,C223,C223,ready,Apartments,Residential,1,flat,2450000.0,104.46,NaN,104.46,104.46,645.0,5911.0,535.0,SIEGFRIED KMIECIAK,NaN,971|54-3567750,971|543567750,971|543567750,Al Barari.xlsx,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2024-04-06,Al Barari,The Residences,Desert Leaf,Desert Leaf 5,16-09,16-09,NaN,ready,Villas,Residential,5,villa,23000000.0,1106.48,1106.48,1288.00,0.00,645.0,5460.0,67.0,Steven Sass,NaN,971|50-9162534,NaN,NaN,Al Barari.xlsx,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2024-04-26,Al Barari,Ixora,NaN,Ixora,BA-R-173,BA-R-173,NaN,off-plan,Villas,Residential,4,villa,6200000.0,180.29,180.29,458.96,0.00,645.0,5015.0,3538.0,zzzzzz,NaN,NaN,NaN,NaN,Al Barari.xlsx,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79204,NaT,Al Hebiah Fourth,VICTORY HEIGHTS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,NaN,NaN,618.59,NaN,NaN,NaN,682.0,528.0,1174.0,LYDIA ROSE HOLLAS,NaN,562360851,NaN,NaN,Victory Heights.xlsx,2024-12-10 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79205,NaT,Al Hebiah Fourth,VICTORY HEIGHTS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,NaN,NaN,618.59,NaN,NaN,NaN,682.0,528.0,1174.0,ANDREAS GEORGE HOLLAS,NaN,553207537,NaN,NaN,Victory Heights.xlsx,2024-12-10 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79206,NaT,Al Hebiah Fourth,VICTORY HEIGHTS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,854.00,NaN,NaN,NaN,682.0,389.0,1096.0,DAVID LAWRIE MATTHEW ROWATT,NaN,544220007,NaN,NaN,Victory Heights.xlsx,2024-12-10 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79207,NaT,Al Hebiah Fourth,VICTORY HEIGHTS - PHASE 2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,NaN,NaN,236.34,NaN,NaN,NaN,682.0,4420.0,1312.0,TAREK HAMDY SHALABY,NaN,588252563,NaN,NaN,Victory Heights.xlsx,2024-12-26 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79208,NaT,Al Hebiah Fourth,VICTORY HEIGHTS - PHASE 2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,NaN,NaN,236.34,NaN,NaN,NaN,682.0,4420.0,1312.0,DANA ALLAWI,NaN,559454876,NaN,NaN,Victory Heights.xlsx,2024-12-26 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Deepcleaning the data

In [72]:
valid_columns = ['Transaction Date', 'Master Location', 'Master Project', 'Building 1', 'BuildingName 2', 'property_number', 'UnitNumber', 'Property Type', 'beds', 'Sub Type', 'Transaction Amount', 'Actual Size', 'Owner Name', 'Phone 1', 'Phone 2', 'Mobile 1', 'Mobile 2', 'Date', 'Secondary Mobile', 'transaction_amount', 'actual_area_sqm', 'plot_area_sqm', 'builtup_area_sqm', 'Master Projects']

In [73]:
df = final_df[valid_columns]

In [74]:
df['Date'] = df['Date'].fillna(df['Transaction Date'])

df['property_number'] = df['property_number'].fillna(df['UnitNumber'])

df['Transaction Amount'] = df['Transaction Amount'].fillna(df['transaction_amount'])

df['Mobile 2'] = df['Mobile 2'].fillna(df['Phone 1'])
df['Mobile 2'] = df['Mobile 2'].fillna(df['Phone 2'])
df['Mobile 2'] = df['Mobile 2'].fillna(df['Mobile 1'])

df['Actual Size'] = df['Actual Size'].fillna(df['actual_area_sqm'])
df['Master Project'] = df['Master Project'].fillna(df['Master Projects'])

In [76]:
cols_to_drop = ['Transaction Date', 'UnitNumber', 'transaction_amount', 'Phone 1', 'Phone 2', 'Mobile 1', 'actual_area_sqm', 'Master Projects']
df = df.drop(columns=cols_to_drop)

In [80]:
old = pd.read_parquet(r'..\data\cleaned_data\uae_realestate.parquet')

In [81]:
old

,Regis,ProcedureValue,Master Project,Master Project Land,Project,Project Lnd,Building No,BuildingNameEn,Size,UnitNumber,DmSubNo,PropertyTypeEn,LandNumber,ProcedurePartyTypeNameEn,NameEn,Mobile,ProcedureNameEn,CountryNameEn,IdNumber,UaeIdNumber,BirthDate
0,2024-03-31,5889469.99,Al Barari,Al Barari,CHORISIA 2 VILLAS,CHORISIA 2 VILLAS,BA-R-101,nan,560.72,nan,4486.0,Building,2208.0,Seller,ABWAB REAL ESTATE LIMITED CO (L.L.C),nan,Complete Delayed Sell,nan,nan,nan,nan
1,2024-03-31,5889469.99,Al Barari,Al Barari,CHORISIA 2 VILLAS,CHORISIA 2 VILLAS,BA-R-101,nan,560.72,nan,4486.0,Building,2208.0,Buyer,CHAKER ZERAIKI,971-56-6038367,Complete Delayed Sell,France,nan,nan,nan
2,2024-03-31,5889469.99,Al Barari,Al Barari,CHORISIA 2 VILLAS,CHORISIA 2 VILLAS,BA-R-101,nan,560.72,nan,4486.0,Building,2208.0,Buyer,CHAKER ZERAIKI,971-56-6038367,Complete Delayed Sell,France,nan,nan,nan
3,2024-03-29,8196624.70,Al Barari,Al Barari,CHORISIA 2 VILLAS,CHORISIA 2 VILLAS,BA-R-137,nan,442.00,nan,4496.0,Building,2218.0,Seller,HAMZA SHABBIR,971-50-9309860,Complete Delayed Sell,nan,nan,nan,nan
4,2024-03-29,8196624.70,Al Barari,Al Barari,CHORISIA 2 VILLAS,CHORISIA 2 VILLAS,BA-R-137,nan,442.00,nan,4496.0,Building,2218.0,Buyer,ABWAB REAL ESTATE LIMITED CO (L.L.C),nan,Complete Delayed Sell,Eritrea,nan,nan,nan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
950238,2018-04-17,4200000.00,VICTORY HEIGHTS,nan,VICTORY HEIGHTS,nan,MORELLA-34,nan,664.71,nan,521.0,Commercial,1167.0,Seller,NOOR BANK P.J.S.C,971-50-6548009,Lease to Own Registration,Saudia,R456921,784193665908021.0,1936-09-17
950239,2018-04-17,4200000.00,VICTORY HEIGHTS,nan,VICTORY HEIGHTS,nan,MORELLA-34,nan,664.71,nan,521.0,Commercial,1167.0,Buyer,PANKHURI BHANDARI,971-55-9579547,Lease to Own Registration,United Kingdom,519927258,784197738326426.0,1977-04-03
950240,2018-01-18,1610000.00,VICTORY HEIGHTS,nan,VICTORY HEIGHTS,nan,Oliva TH 69,nan,249.86,nan,220.0,Commercial,1023.0,Seller,BITA RIAHI,971-50-5529527,Lease Finance Registration,France,09AF32703,784197447504271.0,1974-05-21
950241,2018-01-18,1610000.00,VICTORY HEIGHTS,nan,VICTORY HEIGHTS,nan,Oliva TH 69,nan,249.86,nan,220.0,Commercial,1023.0,Seller,REZA ALAVI,971-50-4595138,Lease Finance Registration,France,15FV00632,784197416296081.0,1974-12-06
950242,2018-01-18,1610000.00,VICTORY HEIGHTS,nan,VICTORY HEIGHTS,nan,Oliva TH 69,nan,249.86,nan,220.0,Commercial,1023.0,Buyer,DUBAI ISLAMIC BANK (PUBLIC JOINT STOCK COMPANY),nan,Lease Finance Registration,nan,nan,nan,nan

In [83]:
import pandas as pd
import numpy as np

def create_unified_data(df1, df2):
    # 1. Define the Semantic Map
    # Key = data1 column name, Value = data2 column name
    mapping = {
        'Regis': 'Date',
        'ProcedureValue': 'Transaction Amount',
        'Master Project Land': 'Master Location',
        'Master Project': 'Master Project',
        'Building No': 'Building 1',
        'BuildingNameEn': 'BuildingName 2',
        'UnitNumber': 'property_number',
        'PropertyTypeEn': 'Property Type',
        'Size': 'Actual Size',
        'NameEn': 'Owner Name',
        'Mobile': 'Mobile 2'
    }
    
    # 2. Prepare data1
    # Rename and drop columns that don't exist in the target schema
    df1_mapped = df1.rename(columns=mapping)
    
    # 3. Handle Data Types
    # Ensure Dates are compatible
    df1_mapped['Date'] = pd.to_datetime(df1_mapped['Date'], errors='coerce')
    df2['Date'] = pd.to_datetime(df2['Date'], errors='coerce')
    
    # Ensure Numeric values are floats (stripping potential formatting if needed)
    for col in ['Transaction Amount', 'Actual Size']:
        df1_mapped[col] = pd.to_numeric(df1_mapped[col], errors='coerce')
        df2[col] = pd.to_numeric(df2[col], errors='coerce')

    # 4. Align Schemas
    # Force df1 to have all columns present in df2 (even if they are empty like 'beds')
    # and remove extra columns from df1 (like 'DmSubNo' or 'IdNumber')
    df1_aligned = df1_mapped.reindex(columns=df2.columns)
    
    # 5. Concatenate
    data3 = pd.concat([df2, df1_aligned], axis=0, ignore_index=True)
    
    return data3

# Execution
data3 = create_unified_data(old, df)

In [92]:
data3.isna().mean() * 100

Master Location        0.044101
Master Project         0.048278
Building 1             0.051678
BuildingName 2         1.930833
property_number        0.073729
Property Type          2.100632
beds                  92.648904
Sub Type              94.532625
Transaction Amount     1.468645
Actual Size            0.045267
Owner Name             0.711349
Mobile 2               0.746902
Date                   0.000097
Secondary Mobile      99.164701
plot_area_sqm         99.989606
builtup_area_sqm      99.204820
dtype: float64

In [98]:
df['Mobile 2'].head(60)

0      971|568677777
1     971|58-5120165
2      971|543567750
3     971|50-9162534
4                NaN
5         0564529588
6     971|56-8687372
7                NaN
8      351|927730885
9      39|3486940020
10    971|50-1970152
11    971|56-6818393
12               NaN
13    971|0544972727
14     971|555956789
15     +971561034760
16        0557008111
17               NaN
18               NaN
19        0506649680
20    971|50-4922296
21    971|56-6691352
22        971|564656
23     971|585872046
24    971|58-9996757
25    971|58-5783361
26               NaN
27     971|564415498
28        0558941244
29     971|549903894
30           971|050
31    971|56-8920920
32     971|556270947
33        0563701821
34     971|566875748
35    971|50-8479489
36    971|56-6396037
37    971|58-5165090
38     971|502116200
39    971|0504584138
40        0508913613
41     92|9232050028
42         674776890
43               NaN
44     971|502374226
45    971|55-5521440
46    971|0555530814
47                 0
48                 0
49         179813395
50     971|588901197
51               NaN
52         641922764
53    971|52-9479050
54    971|58-5006172
55    971|50-5595654
56    971|50-5820857
57    971|54-5657445
58                 0
59            379218
Name: Mobile 2, dtype: object

In [95]:
df

,Master Location,Master Project,Building 1,BuildingName 2,property_number,Property Type,beds,Sub Type,Transaction Amount,Actual Size,Owner Name,Mobile 2,Date,Secondary Mobile,plot_area_sqm,builtup_area_sqm
0,Al Barari,The Neighbourhood,The Neighbourhood C2,C2,C246,Apartments,1,flat,1750000.0,76.76,ABHISHEK MISHRA RAKESH KUMAR MISHRA,971|568677777,2024-04-02,NaN,NaN,NaN
1,Al Barari,The Neighbourhood,The Neighbourhood C2,C2,C244,Apartments,0,flat,1112500.0,47.76,LENKA MAREKOVA,971|58-5120165,2024-04-03,NaN,NaN,NaN
2,Al Barari,The Neighbourhood,The Neighbourhood C2,C2,C223,Apartments,1,flat,2450000.0,104.46,SIEGFRIED KMIECIAK,971|543567750,2024-04-04,NaN,NaN,NaN
3,Al Barari,The Residences,Desert Leaf 5,16-09,16-09,Villas,5,villa,23000000.0,1106.48,Steven Sass,971|50-9162534,2024-04-06,NaN,NaN,NaN
4,Al Barari,Ixora,Ixora,BA-R-173,BA-R-173,Villas,4,villa,6200000.0,180.29,zzzzzz,NaN,2024-04-26,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79204,Al Hebiah Fourth,VICTORY HEIGHTS,NaN,NaN,NaN,NaN,5,NaN,NaN,618.59,LYDIA ROSE HOLLAS,562360851,2024-12-10,NaN,NaN,NaN
79205,Al Hebiah Fourth,VICTORY HEIGHTS,NaN,NaN,NaN,NaN,5,NaN,NaN,618.59,ANDREAS GEORGE HOLLAS,553207537,2024-12-10,NaN,NaN,NaN
79206,Al Hebiah Fourth,VICTORY HEIGHTS,NaN,NaN,NaN,NaN,0,NaN,NaN,854.00,DAVID LAWRIE MATTHEW ROWATT,544220007,2024-12-10,NaN,NaN,NaN
79207,Al Hebiah Fourth,VICTORY HEIGHTS - PHASE 2,NaN,NaN,NaN,NaN,4,NaN,NaN,236.34,TAREK HAMDY SHALABY,588252563,2024-12-26,NaN,NaN,NaN
79208,Al Hebiah Fourth,VICTORY HEIGHTS - PHASE 2,NaN,NaN,NaN,NaN,4,NaN,NaN,236.34,DANA ALLAWI,559454876,2024-12-26,NaN,NaN,NaN